Add silent mode
yoshuawuyts/npm-install-package pull request #2
Opened 2016-09-26 17:30 UTC by RolfKoenders

Add option to disable writing to stdout.
This fixes #1

2016-10-04 12:52 UTC, yoshuawuyts requested changes

2016-10-04 12:52 UTC, yoshuawuyts commented on package.json
> +  "version": "1.1.2",
could you revert the version bump? - on release I'll be bumping this. Thanks!

2016-10-04 12:53 UTC, yoshuawuyts commented
Thanks heaps for the PR; just a lil note and should be good to merge

2016-10-05 08:55 UTC, RolfKoenders commented on package.json
> +  "version": "1.1.2",
Ah oke! Fixed it.

2016-10-05 12:03 UTC, yoshuawuyts approved these changes

2016-10-05 12:03 UTC, merged

2016-10-05 12:05 UTC, yoshuawuyts commented
Released as `v1.1.0` :tada: - thanks heaps!

2016-10-05 12:05 UTC, yoshuawuyts commented
Added as maintainer on GitHub and npm too :sparkles:

2016-10-06 20:05 UTC, RolfKoenders commented
Cool! Appreciated!